"""empty message

Revision ID: f51b657465a8
Revises: 
Create Date: 2022-01-23 10:49:34.937590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51b657465a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ResumeSite', sa.Column('current_plan', sa.String(length=25), nullable=True))
    op.drop_column('ResumeSite', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ResumeSite', sa.Column('status', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('ResumeSite', 'current_plan')
    # ### end Alembic commands ###
